[profile.default]
src = "contracts"
out = "out"
libs = ["contracts/lib"]
solc_version = "0.8.26"
evm_version = "cancun"

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }